# Данные для своры данных о конроллерах
controllers:
  - path: /var/www/payment_system/controllers
    method_prefix: action
    namespace: App\controllers
    class_postfix: Controller

# Пути к директориям файлов
files:


# Дополнительные урлы для добавления
urls:
  - /var/www/payment_system/composer.json

# Роли пользователей
roles:
  - Администратор
  - Преподаватель
  - Слушатель
  - Гость

# Роль по умолчанию
default_role: Гость

# Данные для поключения к кэширующему хранилищу
cache_storage:
  type: redis
  socket: /var/run/redis/redis.sock

# Метка PHPDOC для указания аргумента, по которому следует дополнительно проверять доступ к методу
#access_filter_label: accessFilter

# Аргумента, по которому следует дополнительно проверять доступ к методу
default_access_filter: id

# Метка PHPDOC указывающая, что метод следует обработать Access
#access_label: accessMethod

# Не проверять права на выполнение метода контроллера
access_no_rights_check: noCheck

# Дескриптор указывающий имя схемы, таблицы которой используются при выполнении метода контроллера
access_schema: schema

# Дескриптор, указывающий имя таблицы (модели) для матода контроллера
access_tables: table

# Тип опарации метода контроллера (создание, изменение, удаление, чтение)
access_url_type: urlType

# Идентификатор пользователя-гостя
guest_user_id: 0

# Префикс полей сохранения прав
save_fields_prefix: access_

# Разделитель значений фильтрующих параметров в базе данных
access_separator: ':'

# Запретить несоответствие типов, если реальное значение парметра запроса и аргумента метода совпадают
deny_fuzzy: denyFuzzy

# Проверять возвращаемое значение метода на соответствие типам
check_return: checkReturn


